version: "3"
services:
  pg_primary:
    build:
      context: primary
    ports:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_REPLICATION_USER=repl_user
      - POSTGRES_REPLICATION_PASSWORD=repl_password
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employees_db
    networks:
      default:
        aliases:
          - pg_cluster
  pg_replica:
    build:
      context: replica
    ports:
      - 5432
    depends_on:
      - pg_primary
    environment:
      - POSTGRES_REPLICATION_HOST=pg_primary
      - POSTGRES_REPLICATION_PORT=5432
      - POSTGRES_REPLICATION_USER=repl_user
      - POSTGRES_REPLICATION_PASSWORD=repl_password
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employees_db
    networks:
      default:
        aliases:
          - pg_cluster
volumes:
  pg_data:
