version: "3.3"
services:
  consul:
    image: consul:1.7.1
    ports:
      - 8500:8500
    restart: always
  registrator:
    image: gliderlabs/registrator:latest
    command: consul://consul:8500
    restart: always
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul
  pg_primary:
    image: bhuwanupadhyay/postgres-stream-replication-primary
    ports:
      - 5432
    environment:
      - POSTGRES_REPLICATION_USER=repl_user
      - POSTGRES_REPLICATION_PASSWORD=repl_password
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employees_db
      - POSTGRES_REPLICATION_LOGIN_CONNECTION_LIMIT=100
  pg_replica:
    image: bhuwanupadhyay/postgres-stream-replication-replica
    ports:
      - 5432
    environment:
      - POSTGRES_REPLICATION_USER=repl_user
      - POSTGRES_REPLICATION_PASSWORD=repl_password
      - POSTGRES_REPLICATION_PRIMARY_HOST=pg_primary
      - POSTGRES_REPLICATION_PRIMARY_PORT=5432
    depends_on:
      - pg_primary
    links:
      - pg_primary
  employees_command:
    build:
      context: employees-command
    ports:
      - 8080
    environment:
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://pg_primary:5432/employees_db
      - spring.datasource.username=repl_user
      - spring.datasource.password=repl_password
    depends_on:
      - pg_primary
    links:
      - pg_primary
  employees_query:
    build:
      context: employees-query
    ports:
      - 8080
    environment:
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://replica_lb:5432/employees_db
      - spring.datasource.username=repl_user
      - spring.datasource.password=repl_password
    depends_on:
      - replica_lb
    links:
      - replica_lb